use std::collections::VecDeque;

use bytes::Bytes;
use smoltcp::phy::{self, DeviceCapabilities, Medium};
use smoltcp::time::Instant;

/// A [`phy::Device`] backed by in-memory queues, tying the poll-based
/// `smoltcp` engine to the async world.
///
/// * `ingress` — whole IP packets pushed by
///   [`send_ip_packet`](crate::NetstackHandle::send_ip_packet); the runner
///   hands them to the `smoltcp` interface.
/// * `egress` — IP packets generated by `smoltcp`; the runner forwards them to
///   the application-provided egress channel.
///
/// The device is owned by the background runner and is never shared, so no
/// locking is required here.
pub(crate) struct VirtualDevice {
    mtu: usize,
    pub(crate) ingress: VecDeque<Bytes>,
    pub(crate) egress: VecDeque<Bytes>,
}

impl VirtualDevice {
    pub(crate) fn new(mtu: usize) -> Self {
        Self {
            mtu,
            ingress: VecDeque::new(),
            egress: VecDeque::new(),
        }
    }

    pub(crate) fn push_ingress(&mut self, packet: Bytes) {
        self.ingress.push_back(packet);
    }
}

/// Receive token: hands the raw IP packet bytes to the interface.
pub(crate) struct RxToken {
    pkt: Bytes,
}

impl phy::RxToken for RxToken {
    fn consume<R, F>(self, f: F) -> R
    where
        F: FnOnce(&[u8]) -> R,
    {
        f(&self.pkt)
    }
}

/// Transmit token: captures the buffer filled by the interface and stores it
/// in the device's egress queue.
pub(crate) struct TxToken<'a> {
    device: &'a mut VirtualDevice,
}

impl phy::TxToken for TxToken<'_> {
    fn consume<R, F>(self, len: usize, f: F) -> R
    where
        F: FnOnce(&mut [u8]) -> R,
    {
        let mut buf = vec![0u8; len];
        let result = f(&mut buf);
        self.device.egress.push_back(Bytes::from(buf));
        result
    }
}

impl phy::Device for VirtualDevice {
    type RxToken<'a> = RxToken;
    type TxToken<'a> = TxToken<'a>;

    fn receive(&mut self, _timestamp: Instant) -> Option<(Self::RxToken<'_>, Self::TxToken<'_>)> {
        let pkt = self.ingress.pop_front()?;
        Some((RxToken { pkt }, TxToken { device: self }))
    }

    fn transmit(&mut self, _timestamp: Instant) -> Option<Self::TxToken<'_>> {
        Some(TxToken { device: self })
    }

    fn capabilities(&self) -> DeviceCapabilities {
        let mut caps = DeviceCapabilities::default();
        caps.medium = Medium::Ip;
        caps.max_transmission_unit = self.mtu;
        caps.max_burst_size = None;
        caps
    }
}
