use std::sync::Arc;

use bytes::Bytes;
use tokio::sync::mpsc;

use crate::InterfaceId;
use crate::core::Shared;
use crate::error::NetstackError;
use crate::session::Session;

/// A packet produced by the stack, ready to be written to the real network /
/// TUN device.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EgressPacket {
    /// The interface this packet belongs to.
    pub interface_id: InterfaceId,
    /// The raw IP packet bytes.
    pub data: Bytes,
}

/// Receiver for packets generated by the stack.
pub type EgressReceiver = mpsc::Receiver<EgressPacket>;

/// An IP packet injected into the stack through [`NetstackHandle::send_ip_packet`].
pub(crate) struct IngressPacket {
    pub(crate) interface: InterfaceId,
    pub(crate) data: Bytes,
}

/// Handle to a running netstack instance.
///
/// Use it to feed raw IP packets into the stack and to accept the resulting
/// application-level sessions.
pub struct NetstackHandle {
    pub(crate) shared: Arc<Shared>,
    ingress_tx: mpsc::Sender<IngressPacket>,
    accept_rx: mpsc::UnboundedReceiver<Session>,
}

impl NetstackHandle {
    pub(crate) fn new(
        shared: Arc<Shared>,
        ingress_tx: mpsc::Sender<IngressPacket>,
        accept_rx: mpsc::UnboundedReceiver<Session>,
    ) -> Self {
        Self {
            shared,
            ingress_tx,
            accept_rx,
        }
    }

    /// Inject a raw IP packet (IPv4 or IPv6) received from `interface_id`.
    ///
    /// The packet is queued and processed by the background runner. Returns
    /// `Err` if the interface is unknown or the ingress queue is full
    /// (backpressure).
    pub fn send_ip_packet(
        &self,
        interface_id: InterfaceId,
        packet: Bytes,
    ) -> Result<(), NetstackError> {
        {
            let core = self.shared.core.lock().unwrap();
            if core.slot(interface_id).is_none() {
                return Err(NetstackError::InterfaceNotFound(interface_id));
            }
        }

        let pkt = IngressPacket {
            interface: interface_id,
            data: packet,
        };
        match self.ingress_tx.try_send(pkt) {
            Ok(()) => {
                self.shared.notify_poll();
                Ok(())
            }
            Err(mpsc::error::TrySendError::Full(_)) => Err(NetstackError::ChannelFull),
            Err(mpsc::error::TrySendError::Closed(_)) => Err(NetstackError::ChannelClosed),
        }
    }

    /// Accept the next established session (TCP connection or UDP pseudo-session).
    ///
    /// Returns `None` once the netstack has been dropped and no more sessions
    /// will arrive.
    pub async fn accept(&mut self) -> Option<Session> {
        self.accept_rx.recv().await
    }

    /// The identifiers of all registered interfaces.
    pub fn interface_ids(&self) -> Vec<InterfaceId> {
        let core = self.shared.core.lock().unwrap();
        core.slots.iter().map(|slot| slot.id).collect()
    }
}
